go-jose/go-jose

- jwk.go
- jwk_test.go
Right now JSON unmarshaling fails when the x5u header is present with
the error json: cannot unmarshal string into Go value of type url.URL.
This is because it's a string, we need to parse it ourselves.
> jwk: make x5u header work

- asymmetric.go
- crypter.go
- cryptosigner/cryptosigner.go
- cryptosigner/cryptosigner_test.go
- encoding.go
- go.mod
- jose-util/crypto.go
- jose-util/format.go
- jose-util/generate.go
- jose-util/generator/generate.go
- jose-util/generator/utils.go
- jose-util/main.go
- jwe.go
- jwk.go
- jwk_test.go
- jws.go
- jwt/builder.go
- jwt/builder_test.go
- jwt/claims.go
- jwt/claims_test.go
- jwt/example_test.go
- jwt/jwt.go
- jwt/jwt_test.go
- shared.go
- signing.go
- signing_test.go
- symmetric.go
Avoids an error when importing go-jose/go-jose/v3:
```
module declares its path as: github.com/square/go-jose/v3
but was required as: github.com/go-jose/go-jose/v3
```
Related to https://github.com/square/go-jose/pull/334
> Update module path

- jwt/validation.go
- jwt/validation_test.go
Original issue is https://github.com/square/go-jose/issues/286
And PR for v2 is https://github.com/square/go-jose/pull/369
This PR allows multiple audiences.
Test result is below
```
$ go test ./jwt
ok      github.com/go-jose/go-jose/v3/jwt
```
> Fix allow multiple audiences

- crypter.go
- signing.go
This makes reading the switch statements more consistent and easier to read, since all relevant types are contained within the statement.
> Move type assertions for interface types into switches

- crypter.go
- jwk.go
- shared.go
- signing.go
All places that the public API uses `interface{}` now document the allowable types.
> doc: document all interface{} parameters

- jwk.go
- jwk_test.go
The square/go-jose repo had one commit "Fix EC thumbprint template" which existed on the v2.6.0 tag but not on the v2 branch. This means that it was missed in the recent PR which merged square's v2 branch into this repository's v2 branch. This also means that the current v2.6.0 tag in this repo points to a commit which is not on any branch in this repo.
Fix this situation by producing another merge commit which brings in the one dangling commit from the square repo.
NOTE: this change MUST be merged using the "Merge" strategy, so that the underlying "Fix EC thumbprint template" commit is left untouched, so that the existing v2.6.0 tag can continue to point at it. It MUST NOT be merged using the "Squash and Merge" nor the "Rebase" strategy.
> Merge v2.6.0 from upstream square repo

- jose-util/io.go
- json/bench_test.go
- json/stream_test.go
Per links below:
> Deprecated: As of Go 1.16, this function (ioutil.ReadAll) simply calls io.ReadAll.
> Deprecated: As of Go 1.16, this function (ioutil.ReadFile) simply calls os.ReadFile. 
> Deprecated: As of Go 1.16, this function (ioutil.WriteFile) simply calls os.WriteFile. 
> Discard is an io.Writer on which all Write calls succeed without doing anything. Deprecated: As of Go 1.16, this value (ioutil.Discard) is simply io.Discard. 
1. https://pkg.go.dev/io/ioutil#ReadAll
2. https://pkg.go.dev/io/ioutil#ReadFile
3. https://pkg.go.dev/io/ioutil#WriteFile
4. https://pkg.go.dev/io/ioutil#pkg-variables
> Replace deprecated iotuil functions with io and os functions

- jwk.go
- jwk_test.go
This commit allows getting a thumbprint for the type OpaqueSigner. So if a key is backed by a custom signer, for example, a YubiKey or a cloud signer, we should be able to get the thumbprint for it as long as the public key is one of the supported ones.
> Add Thumbprint support for opaque signers

- cryptosigner/cryptosigner.go
- cryptosigner/cryptosigner_test.go
This commit returns the proper algorithm for ECDSA keys. The previous version returned ES256, ES384, and ES521 when only one was valid.
This fixes the "This could be more precise" comment.
@pgporada, @aarongable
> Return the proper algorithm for ECDSA keys

- symmetric.go
This commit increases the number of PBKDF2 iterations used in PBES2 from 100k to 600k. In past few months the new password recommendations are to use at least 600k with SHA-256.
See https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2
PS: I implemented PBES2 support in the original `square/go-jose` a few years ago.
> Increase the number of PBKDF2 iterations to 600k

- doc.go
- json/decode.go
- json/encode.go
- json/stream.go
- jwt/claims.go
- jwt/doc.go
- opaque.go
Apply `gofmt` 1.20 formatting changes.
```console
$ gofmt -l -s -w *.go json/*.go jwt/*.go
```
(no changes in other directories: `jose-util/**`, `cryptosigner`, `cipher`)
> gofmt 1.20

- .github/workflows/go.yml
Bump golang to 1.21 GA
- test passed https://github.com/arukiidou/go-jose/pull/1
> Bump golang to 1.21 GA

- jwt/validation.go
- jwt/validation_test.go
Per #23, PR #10 (unreleased) made the authorization properties of Claims.Validate more relaxed. Given that people may have been relying on those authorization properties, we shouldn't make that change without a change in API surface or a major version bump.
> Revert pull request #10 (multiple audiences)

- crypter.go
- crypter_test.go
In 7d3b437c, a lint was fixed in this function: `err` was ineffectually assigned to. However, the fix should have been to handle the error rather than to ignore it with `_`.
> DecryptMulti: handle decompression error

- encoding.go
- jwe.go
- jws.go
Use concatenate instead of `fmt.Sprintf(...)`. Reduce memory allocation.
on my machine: m1 pro, 32gb ram.
```
name                 old time/op    new time/op    delta
CompactSerialize-10    1.32µs ± 1%    1.12µs ± 1%  -15.40%  (p=0.000 n=19+19)
name                 old alloc/op   new alloc/op   delta
CompactSerialize-10    2.21kB ± 0%    2.13kB ± 0%   -3.62%  (p=0.000 n=20+20)
name                 old allocs/op  new allocs/op  delta
CompactSerialize-10      25.0 ± 0%      20.0 ± 0%  -20.00%  (p=0.000 n=20+20)
```
> jwe/CompactSerialize: improve performance.

- jose-util/go.mod
Hi, I get the following error when I `go get -u jose-util`.
```bash
$ go get -u github.com/go-jose/go-jose/jose-util
go: github.com/go-jose/go-jose/jose-util@upgrade (v0.0.0-20231117013707-053c9bf3d6ce) requires github.com/go-jose/go-jose/v3@v3.0.0-00010101000000-000000000000: github.com/go-jose/go-jose/v3@v3.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```
Perhaps updating `go-jose` in `go.mod` will solve the problem, but since v3.0.1 has been released, I have updated that. 
Thank you in advance.
> Updated go-jose v3.0.0 to v3.0.1 in jose-util

- go.mod
In anticipation of API-breaking changes.
> go.mod: bump major version to v4

- cryptosigner/cryptosigner_test.go
- doc_test.go
- jws.go
- jws_test.go
- jwt/builder.go
- jwt/builder_test.go
- jwt/example_test.go
- jwt/jwt.go
- jwt/jwt_test.go
- opaque_test.go
- signing_test.go
> jws: Add expected algorithms for signatures

- jwt/validation.go
- jwt/validation_test.go
Previously, the `Expected.Audience` field meant "all of these audiences must be present in the token." But that doesn't really make sense with the spec:
https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3
Instead, rename the field to `AnyAudience` and changes its semantics to mean "there must be an intersection between this set and the set of audiences in the token."
Re-land of #10 on the `main` (v4) branch. Followup of #23 and #24. cc @shnmorimoto
> jwt: use AnyAudience matching

- jws.go
- jwt/builder_test.go
- jwt/jwt.go
- jwt/jwt_test.go
Inspired by the "Sign/encrypt confusion" attack in:
https://i.blackhat.com/BH-US-23/Presentations/US-23-Tervoort-Three-New-Attacks-Against-JSON-Web-Tokens-whitepaper.pdf
And the conclusions and remediations section:
> For JWT/JOSE library developers:
> Never accept JWTs that are encrypted with a password or public key
> Limit JWT encryption types

- jws_test.go
- jwt/builder_test.go
- jwt/example_test.go
- jwt/jwt_test.go
- signing.go
- signing_test.go
- symmetric.go
Update the test cases that were using undersized keys. For `hmacSignedToken`, since it had to be regenerated anyhow, move generation into an `init()` function.
For the example tests, replace panics with print and exit. This allows multiple tests to fail during a given run, since example tests do not catch panics in the same way ordinary tests do.
Fixes #83
> Enforce minimum length for HMAC keys

- README.md
Also:
- move the Versions stanza to the top
- remove the Help Wanted
- remove the doc / build badges
Since this is not the main branch, it will mainly be viewed on pkg.go.dev after we make a patchlevel release.
> doc: in v3 branch's README, point to v4 as latest

- asymmetric.go
- signing_test.go
This PR fixes #27 for the v2 branch. Cherry picked from commit b7b32c1007cb6e57ac14c6959f6546ca1591f591 (#39).
> Fix TestSignerWithBrokenRand for go1.20 (v2 branch)

- signing.go
`Verify` calls `DetachedVerify` which calls `tryJWKS`.
> JSONWebKeySet is supported as well

- CHANGELOG.md
- crypter.go
- encoding.go
- encoding_test.go
Backport from #106.
Note that there was a merge conflict on the CHANGELOG and I decided to just accept all the v4 entries. It's okay for the v3 branch's CHANGELOG to also talk about v4 releases. I'll send a separate PR updating the v4 CHANGELOG to include v3.0.3.
> v3: backport decompression limit fix

- shared.go
Most of the errors in the shared source have a dedicated error value
except for a couple that got away:
* x5c header missing in the JWT header
* An unsupported/unknown elliptic curve is found
This commit defines the error values for those cases.
This would be helpful to https://github.com/distribution/distribution project when discriminating between different errors during token validation.
> Define error values for missing x5c header and unsupported elliptic curves

- .github/dependabot.yml
Configure dependabot to run weekly for Go and Github Actions
> Add dependabot configuration for Go and GH Actions

- opaque.go
- opaque_test.go
Also, remove TestOpaqueKeyRoundtripJWE test case, which is expensive (because it incidentally uses the large default PBES2Count) and isn't testing reachable code. It can be restored if/when we fix the API for OpaqueKeyEncrypter so it can be implemented (and possibly pass along PBES2 parameters).
Fixes #112, updates #114
Note: I tried simply exporting `encryptKey` as `EncryptKey` and adding parameters, but it wound up getting more involved because we would also have to export the return type `recipientInfo`, which in turn contains the unexported `*rawHeader`. For now this documents the status quo (OpaqueKeyEncrypter doesn't work) and speeds up our tests dramatically (11s on my machine).
> doc: note OpaqueKeyEncrypter can't be implemented

- jwk.go
- jwk_test.go
This reverts commit 3e2bbef724ae666f9e6691659bd46bc0c3e0c7aa, "Unmarshal jwk keys with unsupported key type or algorithm into empty ... (#26)"
I accidentally merged that PR into v3, but per our README, the v3 branch is getting security updates but not functionality updates.
> Revert #26 (ignore unsupported JWKs in Sets)

- jwk.go
- jwk_test.go
- shared.go
Port of #26 to main branch, along with some fixes:
- reset the list of keys when unmarshaling
- return UnsupportedKeyType instead of internal error
- update tests to separately test JWK parsing (should return error for unsupported) and JWK Set parsing (should ignore unsupported JWKs)
> JSONWebKeySet: ignore unsupported key types

- jwk.go
As noted here https://github.com/go-jose/go-jose/pull/130#pullrequestreview-2179088936
The error type `errUnsupportedJWK` is never used.
In addition, swapped out a use of `fmt.Errorf()` with the slightly more performant `errors.New()`.
> Remove unused JWK error type

- jwk.go
Noted a few `fmt.Errorf()` errors that can be exited early.
> Short circuit return errors from `JSONWebKey.UnmarshalJSON()`

- README.md
See https://www.linuxfoundation.org/resources/publications/understanding-us-export-controls-with-open-source-projects
As an oepn source project, we can make this globally available.
Also, there's not really any encryption software in go-jose - that's all in golang's crypto libraries.
> Remove export disclaimer

- jwe.go
- jws.go
- jws_test.go
In compact JWS/JWE, don't allow unbounded number of splits.
Count to make sure there's the right number, then use SplitN.
> Don't allow unbounded amounts of splits

- jws.go
The various `Parse` functions in `jws.go` that construct `jose.JSONWebSignature` take a slice of acceptable signature algorithms. We now document its purpose and usage. While I was in there, I also added a reference to RFC 7515 for detached paylods.
Fixes #162
> Document `signatureAlgorithms` argument

- jwe.go
- jws.go
- jws_test.go
Backport #167 
git cherry-pick 99b346cec4e86d102284642c5dcbe9bb0cacfc22
> Backport fix 167

- .github/workflows/go.yml
Previously done in the /v3 branch, this is for `main` (v4)
> Bump CI Go to 1.23.x and 1.24.x

- go.mod
- go.sum
- jwk_test.go
We only use it in a few small places.
Without cmp.Diff, we might not get as nice test failures, but it's not too hard to use an external diff tool if something were to break.
> Drop go-cmp dependency

- jwe.go
- jwe_test.go
- jws.go
- jws_test.go
See also https://go-review.googlesource.com/c/oauth2/+/655455
name                  old time/op    new time/op    delta
ParseSignedCompat-16    1.95µs ± 1%    1.91µs ± 1%  -1.83%  (p=0.000 n=9+10)
name                  old alloc/op   new alloc/op   delta
ParseSignedCompat-16    3.26kB ± 0%    3.21kB ± 0%  -1.47%  (p=0.000 n=10+10)
name                  old allocs/op  new allocs/op  delta
ParseSignedCompat-16      45.0 ± 0%      44.0 ± 0%  -2.22%  (p=0.000 n=10+10)
> jws: improve performance and allocations for ParseSignedCompact

- jwk.go
Added a missing quote to the unknown curve error message. 
Go test is passing - 
```
$ go test
PASS
ok      github.com/go-jose/go-jose/v4   4.432s
```
Go fmt is good too
```
$ go fmt 
$ echo $?
0
```
> Add missing quote to unknown curve message #170

- jwe.go
From the context, it seems that the enc variable should be used.
Fixes: 9b5800e ("Require specifying algorithms for ParseEncrypted (#69)")
> Fix incorrect validation

- .github/workflows/go.yml
- go.mod
- go.sum
- jwe_test.go
- jws_test.go
- symmetric.go
- symmetric_go124.go
- symmetric_legacy.go
- symmetric_test.go
- Uses a build tag to decide between stdlib pbkdf2 implementation or `x/` legacy implementation based on Go version
- Restores benchmarks to legacy syntax
- Sets go.mod minimum version to 1.23.0
- Since Go 1.21, the `.0` should be added to indicate the minimum version of the toolchain AFAIK, notably it excludes prereleases https://tip.golang.org/doc/toolchain#version So I went with it instead of going to the previous `1.23`
- Restores 1.23 CI workflow
> Restore Go 1.23 compatibility

- jwk.go
The switch statement is exited subsequent to the first condition that evaluates to true, yet it is evident from the context that the intention was to cover all possibilities.
Found by PostgresPro
Fixes: 98e5a54 ("Print all missing fields at once")
> Improve error message for invalid private keys

- crypter.go
- crypter_test.go
This PR fixes an issue where JSONWebKey is marked as a valid type in Recipient: 
```
type Recipient struct {
Algorithm KeyAlgorithm
// Key must have one of these types:
//  - ed25519.PublicKey
//  - *ecdsa.PublicKey
//  - *rsa.PublicKey
//  - *JSONWebKey
//  - JSONWebKey
//  - []byte (a symmetric key)
//  - Any type that satisfies the OpaqueKeyEncrypter interface
//
// The type of Key must match the value of Algorithm.
Key        interface{}
KeyID      string
PBES2Count int
PBES2Salt  []byte
}
```
But is rejected further down the line when calling `makeJWERecipient()`.
I've also added tests and edited the name to show the difference in between the two types. 
Thanks!
> Add JSONWebKey type to makeJWERecipient

- jwk_test.go
- jws_test.go
- jwt/claims_test.go
- testutils/assert/equal.go
- testutils/assert/equal_test.go
These functions were used few places, and could generally be replaced with a simple `if` and a more informative error message, or a more specific assert function.
Follow up to #197
> testutils/assert: remove True, Nil, NotNil

- crypter.go
- shared.go
- signing.go
- signing_test.go
The only critical header that go-jose supports is b64 from RFC7797.
go-jose correctly only respects that header if it appears in a protected header. go-jose correctly rejects unknown critical headers.
However, go-jose does not reject a JWS which contains a critical b64 unprotected header.
I don't believe this has any security impact, as the only place this is exposed is via the Signature header members which expose unprotected headers, and so a library user is already aware they are not to be trusted. The 'critical' behavior (of not base64-encoding the value, defined in RFC7797) is not influenced here.
Return a new ErrUnsupportedCriticalHeader error exported as a constant.
Reported by: Muhammad Noman Ilyas @AL-Cybision
> Reject JWS with an unprotected critical b64 header
